# نسخه فیلد version قدیمیه و لازم نیست؛ حذفش کن
services:
  postgres:
    image: postgres:17
    container_name: erp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: erp_backend
      POSTGRES_USER: strapi_admin
      POSTGRES_PASSWORD: "13751357"

    ports:
      - "127.0.0.1:5348:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U strapi_admin -d erp_backend -h 127.0.0.1 -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres-data:
    driver: local
